import configparser

config = configparser.ConfigParser()
config.read("config/config.ini")

# URL FOR WEATHER
BASE_URL_WEATHER = config["DEFAULT"]["BASE_URL_WEATHER"]
WEATHER_CITY = config["DEFAULT"]["WEATHER_CITY"]
WEATHER_APP_ID = config["DEFAULT"]["WEATHER_APP_ID"]
WEATHER_UNITS = config["DEFAULT"]["WEATHER_UNITS"]

# URL AND CREDENTIALS FOR ECO BIKES
API_CLIENT_ID = config["DEFAULT"]["API_CLIENT_ID"]
API_CLIENT_SECRET = config["DEFAULT"]["API_CLIENT_SECRET"]
URL_SYSTEM_INFORMATION = config["DEFAULT"]["URL_SYSTEM_INFORMATION"]
URL_STATION_STATUS = config["DEFAULT"]["URL_STATION_STATUS"]
URL_STATION_INFO = config["DEFAULT"]["URL_STATION_INFO"]
